name: Test Action

on:
  push:
    branches:
      - main   # or any other branch you want to trigger this action on

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 21f2001306@ds.study.iitm.ac.in
        run: echo "Hello, world!"
